export type {
  ClickRecordedActionDetail,
  CloudReplayTarget,
  CodegenOptions,
  CloseTabRecordedActionDetail,
  DblclickRecordedActionDetail,
  FlowRecorderSnapshot,
  GoBackRecordedActionDetail,
  GoForwardRecordedActionDetail,
  KeypressRecordedActionDetail,
  LocalReplayTarget,
  NavigateRecordedActionDetail,
  NewTabRecordedActionDetail,
  RawFlowRecorderClickEvent,
  RawFlowRecorderDblclickEvent,
  RawFlowRecorderEvent,
  RawFlowRecorderGoBackEvent,
  RawFlowRecorderGoForwardEvent,
  RawFlowRecorderKeypressEvent,
  RawFlowRecorderNavigateEvent,
  RawFlowRecorderReloadEvent,
  RawFlowRecorderScrollEvent,
  RawFlowRecorderSelectOptionEvent,
  RawFlowRecorderTypeEvent,
  RecorderInitialPageState,
  RecordedAction,
  RecordedActionDetail,
  RecordedActionKind,
  RecorderPageState,
  ReplayTarget,
  RecordingOptions,
  ReloadRecordedActionDetail,
  ScrollRecordedActionDetail,
  SelectOptionRecordedActionDetail,
  SwitchTabRecordedActionDetail,
  TypeRecordedActionDetail,
} from "./types.js";
export {
  createFlowRecorderInstallScript,
  FLOW_RECORDER_DRAIN_SCRIPT,
  FLOW_RECORDER_INSTALL_SCRIPT,
} from "./browser-scripts.js";
export { FlowRecorderCollector } from "./event-collector.js";
export type { FlowRecorderCollectorOptions, RecorderRuntimeAdapter } from "./event-collector.js";
export { generateReplayScript } from "./codegen.js";
